services:
  mongodbcontainer:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nodecontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongodbcontainer:27017/myDatabase

    depends_on:
      - mongodbcontainer
    ports:
      - "3000:3000"
   

volumes:
  mongodb_data:
